### ISSUE TITLE
Is there a complete example for this？like simple webIDE

### ISSUE THREAD

**Issue by huruji** [gins3000/node-debugprotocol-client#1]

**Comment by gins3000** [comment]
This is simply an implementation of the [VSCode Debug Adapter Protocol](https://microsoft.github.io/debug-adapter-protocol/) as a NodeJS module. There is no example (by myself or to my knowledge) other than what you can find in the ReadMe: how to set up a client, connect it to an [Adapter](https://microsoft.github.io/debug-adapter-protocol/implementors/adapters/), how to send [Requests](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_Initialize) (e.g. setting breakpoints) and listen to [Events](https://microsoft.github.io/debug-adapter-protocol/specification#Events_Initialized) (e.g. a breakpoint was hit).

If you have any specific questions, I'll try to answer them to the best of my knowledge :)
